#!/bin/bash

if pgrep -x "hypridle" > /dev/null; then 
    pkill hypridle
    notify-send "Idle Inhibit" "Disabled"
else
    nohup hypridle >/dev/null 2>&1 & 
    notify-send "Idle Inhibit" "Enabled"
fi
